CREATE TABLE Members (
	EmployeeId VARCHAR(4) NOT NULL CONSTRAINT PK_Employees PRIMARY KEY,
	Name NVARCHAR(200) NOT NULL,
	Email NVARCHAR(200) NOT NULL,
	Mobile NVARCHAR(200) NOT NULL,
)
GO

CREATE TABLE Cards (
	CardId VARCHAR(16) NOT NULL CONSTRAINT PK_CardUsers PRIMARY KEY,
	EmployeeId VARCHAR(4) NOT NULL CONSTRAINT FK_CardUsers FOREIGN KEY (EmployeeId) REFERENCES Members (EmployeeId),
	Pin  VARCHAR(4)
)
GO

CREATE TABLE CardTransactions (
	TransactionId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CardTransactions PRIMARY KEY,
	CardId VARCHAR(16) NOT NULL CONSTRAINT FK_CardTransactions FOREIGN KEY (CardId) REFERENCES Cards (CardId),
	Date DATETIME NOT NULL,
	Amount DECIMAL(10,2) NOT NULL DEFAULT 0, 
	Balance DECIMAL(10,2) NOT NULL DEFAULT 0, 
)
GO

